/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ventanas1;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
/**
 *
 * @author User
 */
public class Ponchar extends javax.swing.JFrame {
    String user = Conexion.user;
    String clave = Conexion.clave;
    String url = Conexion.url;
    Connection con;
    Statement stmt;
    ResultSet rs;
    String datos[] = new String [4]; 
    DefaultTableModel modelo = new DefaultTableModel();
   
    
    /**
     * Creates new form Inicio
     */
    public Ponchar() {
        
        initComponents();
        this.setTitle("Facturar - Contabilidad");
        this.setLocationRelativeTo(null);
        try {
                Class.forName("com.mysql.cj.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Ponchar.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        jLabelFecha.setText(fecha());
      buscarCliente();
       buscarProducto();
       sumaHoras();
       
       
       
        

        
        
          
       
    }
    public Image getIconImage(){
       Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes1/icono.png"));
       return retValue;
    }
    
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonListo2 = new javax.swing.JButton();
        jButtonListo1 = new javax.swing.JButton();
        jLabelPrecio7 = new javax.swing.JLabel();
        jTextFieldNombreReg = new javax.swing.JTextField();
        jLabelFecha = new javax.swing.JLabel();
        jLabelMinutos = new javax.swing.JLabel();
        jLabelHoras = new javax.swing.JLabel();
        jLabelPrecio8 = new javax.swing.JLabel();
        jLabelPrecio5 = new javax.swing.JLabel();
        jComboBoxNombre = new javax.swing.JComboBox<>();
        jLabelPrecio6 = new javax.swing.JLabel();
        jScrollPaneProducto = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        jButtonListo = new javax.swing.JButton();
        jButtonCancelar1 = new javax.swing.JButton();
        jLabelPrecio4 = new javax.swing.JLabel();
        jButtonInicio = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();
        jLabelSumas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonListo2.setBackground(new java.awt.Color(255, 255, 255));
        jButtonListo2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonListo2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonListo2.setText("REGISTRAR TRABAJADOR");
        jButtonListo2.setContentAreaFilled(false);
        jButtonListo2.setOpaque(true);
        jButtonListo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListo2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonListo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, 40));

        jButtonListo1.setBackground(new java.awt.Color(201, 116, 88));
        jButtonListo1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonListo1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonListo1.setText("SALIDA");
        jButtonListo1.setContentAreaFilled(false);
        jButtonListo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListo1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonListo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 380, -1, 40));

        jLabelPrecio7.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPrecio7.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelPrecio7.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPrecio7.setText("NOMBRE:");
        jLabelPrecio7.setOpaque(true);
        getContentPane().add(jLabelPrecio7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 120, -1));
        getContentPane().add(jTextFieldNombreReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 220, 30));

        jLabelFecha.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFecha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelFecha.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFecha.setOpaque(true);
        getContentPane().add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 320, 240, 40));

        jLabelMinutos.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMinutos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelMinutos.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMinutos.setOpaque(true);
        getContentPane().add(jLabelMinutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 540, 240, 40));

        jLabelHoras.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHoras.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelHoras.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHoras.setOpaque(true);
        getContentPane().add(jLabelHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 590, 240, 40));

        jLabelPrecio8.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPrecio8.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelPrecio8.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPrecio8.setText("SUMA HORAS:");
        jLabelPrecio8.setOpaque(true);
        getContentPane().add(jLabelPrecio8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 590, 190, -1));

        jLabelPrecio5.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPrecio5.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelPrecio5.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPrecio5.setText("SUMA MINUTOS:");
        jLabelPrecio5.setOpaque(true);
        getContentPane().add(jLabelPrecio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 540, 190, -1));

        jComboBoxNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBoxNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 260, 240, 40));

        jLabelPrecio6.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPrecio6.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelPrecio6.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPrecio6.setText("NOMBRE:");
        jLabelPrecio6.setOpaque(true);
        getContentPane().add(jLabelPrecio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 120, -1));

        TablaDatos = new javax.swing.JTable(){
            public boolean isCellEditable(int riwIndex, int colIndex){
                return false;
            }
        };
        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaDatos.getTableHeader().setReorderingAllowed(false);
        jScrollPaneProducto.setViewportView(TablaDatos);

        getContentPane().add(jScrollPaneProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 680, 320));

        jButtonListo.setBackground(new java.awt.Color(201, 116, 88));
        jButtonListo.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonListo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonListo.setText("ENTRADA");
        jButtonListo.setContentAreaFilled(false);
        jButtonListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, -1, 40));

        jButtonCancelar1.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCancelar1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonCancelar1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/x cancelar.png"))); // NOI18N
        jButtonCancelar1.setText("CANCELAR");
        jButtonCancelar1.setBorderPainted(false);
        jButtonCancelar1.setContentAreaFilled(false);
        jButtonCancelar1.setDefaultCapable(false);
        jButtonCancelar1.setOpaque(true);
        jButtonCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 230, 50));

        jLabelPrecio4.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPrecio4.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelPrecio4.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPrecio4.setText("FECHA:");
        jLabelPrecio4.setOpaque(true);
        getContentPane().add(jLabelPrecio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 90, -1));

        jButtonInicio.setBackground(new java.awt.Color(201, 116, 88));
        jButtonInicio.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonInicio.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/inicio.png"))); // NOI18N
        jButtonInicio.setBorderPainted(false);
        jButtonInicio.setContentAreaFilled(false);
        jButtonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 70, -1, -1));

        jLabelLogo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/cajon_1.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        jLabelFondo.setBackground(new java.awt.Color(0, 0, 0));
        jLabelFondo.setOpaque(true);
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1310, 650));

        jLabelSumas.setText("jLabel1");
        getContentPane().add(jLabelSumas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void buscarProducto(){

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("TRABAJADOR");
        modelo.addColumn("FECHA");
        modelo.addColumn("TIPO");
        
        
        TablaDatos.setModel(modelo);

        String datos[] = new String [4];
         
        try {
            con = DriverManager.getConnection(url, user, clave);
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM trabajadores ");
            while(rs.next()){
                
                datos[0]= rs.getString(1);
                datos[1]= rs.getString(2);
                datos[2]= rs.getString(3);
                datos[3]= rs.getString(4);

                modelo.addRow(datos);
            }
            
            TablaDatos.setModel(modelo);
            TableColumn columna = TablaDatos.getColumn("ID");
            
            columna.setMinWidth(48);
            columna.setMaxWidth(48);

            
        } catch (SQLException ex) {
            Logger.getLogger(Vendido.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    
    void buscarCliente(){
        try {
             
            con = DriverManager.getConnection(url, user, clave);
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM nombretrabajador ORDER BY nombre ASC ");

                while(rs.next()){
                    jComboBoxNombre.addItem(rs.getString(2));
                }
        
            
        } catch (SQLException ex) {
            
        }
        
    }
    
    
    
     public static String fecha(){
       Date fecha = new Date();
       SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYYY HH:mm");
       return formatofecha.format(fecha);
    }
     
    void sumaHoras(){
        int suma=0;
        int horas=0;
        int minutos=0;
        System.out.println("Entré");
        for (int i = 0; i < modelo.getRowCount(); i++) {
            if(modelo.getValueAt(i, 3).toString().equals("ENTRADA")){
                System.out.println("Entré");
                String horario = modelo.getValueAt(i, 2).toString();
                String hora = horario.substring(11,12);
                String minuto = horario.substring(14,15);
                
                String horario2 = modelo.getValueAt(i+1, 2).toString();
                String hora2 = horario2.substring(11,12);
                String minuto2 = horario2.substring(14,15);
                
                horas = horas +(Integer.parseInt(hora2)-Integer.parseInt(hora));
                minutos = minutos + Math.abs(Integer.parseInt(minuto2) - Integer.parseInt(minuto));
                     
                i++;
            }
        }
        suma =(horas*60)+minutos;
        jLabelMinutos.setText(String.valueOf(suma));
        suma = horas + (minutos/60) ;
        jLabelHoras.setText(String.valueOf(suma));
        
    }
     
    
    
    
    private void jButtonListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListoActionPerformed
        try {
                con = DriverManager.getConnection(url, user, clave);
                stmt = con.createStatement();
                
                stmt.executeUpdate("INSERT INTO trabajadores VALUES('0' , '"+jComboBoxNombre.getSelectedItem().toString()+"',"
                        + " '"+jLabelFecha.getText()+"', 'ENTRADA')");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "error");
                
            }
        buscarProducto();
        sumaHoras();
    }//GEN-LAST:event_jButtonListoActionPerformed

    private void jButtonCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelar1ActionPerformed
        
        
    }//GEN-LAST:event_jButtonCancelar1ActionPerformed

    private void jButtonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioActionPerformed
        Inicio I = new Inicio();
        I.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonInicioActionPerformed

    private void jComboBoxNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNombreActionPerformed

    private void jButtonListo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListo2ActionPerformed
        if(jTextFieldNombreReg.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "No ingresó el nombre");
        }else{
            try {
                con = DriverManager.getConnection(url, user, clave);
                stmt = con.createStatement();
                
                stmt.executeUpdate("INSERT INTO nombretrabajador VALUES('0' , '"+jTextFieldNombreReg.getText()+"')");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "error");
                
            }
            JOptionPane.showMessageDialog(null, "Registro existo");
            
        }
    }//GEN-LAST:event_jButtonListo2ActionPerformed

    private void jButtonListo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListo1ActionPerformed
       try {
                con = DriverManager.getConnection(url, user, clave);
                stmt = con.createStatement();
                
                stmt.executeUpdate("INSERT INTO trabajadores VALUES('0' , '"+jComboBoxNombre.getSelectedItem().toString()+"',"
                        + " '"+jLabelFecha.getText()+"', 'SALIDA')");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "error");
                
            }
        buscarProducto();
        sumaHoras();
    }//GEN-LAST:event_jButtonListo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ponchar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ponchar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ponchar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ponchar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ponchar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable TablaDatos;
    public javax.swing.JButton jButtonCancelar1;
    private javax.swing.JButton jButtonInicio;
    private javax.swing.JButton jButtonListo;
    private javax.swing.JButton jButtonListo1;
    private javax.swing.JButton jButtonListo2;
    private javax.swing.JComboBox<String> jComboBoxNombre;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelHoras;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMinutos;
    private javax.swing.JLabel jLabelPrecio4;
    private javax.swing.JLabel jLabelPrecio5;
    private javax.swing.JLabel jLabelPrecio6;
    private javax.swing.JLabel jLabelPrecio7;
    private javax.swing.JLabel jLabelPrecio8;
    private javax.swing.JLabel jLabelSumas;
    private javax.swing.JScrollPane jScrollPaneProducto;
    private javax.swing.JTextField jTextFieldNombreReg;
    // End of variables declaration//GEN-END:variables
}
